language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: myNlG4pM80Htz7pfBPJ7JkRaz7tS+IdL6pxMG6XlShpkNQGHXRu4b0EllCaQr6hqDRsJwLL8I7wn29VK5YlPzCHc5+AZgxEwzx3PHu17nvQQC/BjoyJAjIpldkllsnlHXqN91TU0DfXt1njV4Kl1z5M7npPrEh/Hl8x1xNBXMiXMsM7z0m8Z+Uoem7nE54eS6gO7K9LI38N0bB+BDGT8zXRtZqotN4GFK5qzNzcm0YYReM+QJd2UevdExZ9B4CKMaSSxdZGw7HguwCmP0+AiSSxtbjPFDCZ45gr21Y+P3WFyp0zfsZ7ZQhkirNE1w8VZ9GIEmOguOqT6eZ5aUnRX92OWT8MTzdO3Tk0iCKqLGadCq1IDERmk/LBhvpasgRjDSWiiA27DClaWtM8Bpd789de828Z3gHxReJWzRPPsoZJXalpspHFbQToXEfwvag1SGozHIcjpe6021RYS5lVPNih0QNohOidoL+eY7rhfR5KpFjIoLBJxCJsw07c5n30R7mRau4InfohTObjzQoph4dRogBezFak5aZzkJNHYZQxi3R3UbePIkQb42gbXaP3Tsl3vO/CCVvIl6hgds0YrPOarlkrigEhBPj2P+gnhDXdlyVuxfzlfL4BVADX8LZm2qxrvRZyFeGA5QYh0ZDjkKaiXGaWd94AxikpwWh16BJk=
